export const SERVICES = [
    {
        id: 1,
        name: "Hair Cut",
        marathi: "हेअर कट",
        price: 200,
        duration: "20 Min",
        category: "Hair",
        description: "Classic haircut with premium styling.",
        image: null,
    },
    {
        id: 2,
        name: "Beard Trim",
        marathi: "दाढी ट्रिम",
        price: 100,
        duration: "15 Min",
        category: "Beard",
        description: "Professional beard styling.",
        image: null,
    },
    {
        id: 3,
        name: "Hair Spa",
        marathi: "हेअर स्पा",
        price: 700,
        duration: "45 Min",
        category: "Hair",
        description: "Deep nourishment treatment.",
        image: null,
    },
    {
        id: 4,
        name: "Facial",
        marathi: "फेशियल",
        price: 600,
        duration: "40 Min",
        category: "Face",
        description: "Professional facial treatment.",
        image: null,
    },
    {
        id: 5,
        name: "Hair Color",
        marathi: "हेअर कलर",
        price: 1200,
        duration: "60 Min",
        category: "Hair",
        description: "Premium hair coloring.",
        image: null,
    },
];